blockchain:
  #挖矿难度值,越大越难挖
  mine_difficulty_value: 23
  #挖矿奖励代币数量
  token_reward_num: 25
  #交易池大小(满足多少条交易才开始发送挖矿信息)
  trade_pool_length: 2
  #日志存放路径
  log_path: "./"
  #中文助记词路径
  chinese_mnemonic_path: "./chinese_mnemonic_world.txt"
network:
  #本地监听IP
  listen_host: "192.168.0.164"
  #本地监听端口
  listen_port: "9000"
  rendezvous_string: "meetme"
  #p2p网络连接通道名称
  protocol_id: "/chain/1.1.0"
